### PR TITLE
add stats functions

### PR DESCRIPTION
**Pull request by thelittlefireman**
#11 
ping @ludeeus ;)

### CODE REVIEW

**Comment by digiblur** [comment]
Nice. Don't have to go around the world with grafana to Influx to HA for docker info.

**Comment by philhawthorne** [comment]
Awesome!

I've merged this to the dev branch for me to test, then I'll bump the version and push it to master. 

Thanks a lot

**Comment by philhawthorne** [comment]
Thanks @thelittlefireman 

I tested this on my Synology NAS, and unfortunately the response never closed. I suspect my NAS is streaming the response of the call to stats incorrectly. Might be an issue with other systems.

I tested this on a local docker dev machine I have here, and it works great!

Thanks again

**Comment by thelittlefireman** [comment]
Damn =s I test it only a local Unix machine and I plan to set it on a synology, I will let you know if it works better on mine.

Thanks for the merge :)

**Comment by ludeeus** [comment]
@thelittlefireman 
https://github.com/ludeeus/custom_component_hadockermon/releases/tag/1.3.0
Added optional attributes for network and memory, have no idea on how to do the math for CPU metrics :P

**Comment by thelittlefireman** [comment]
Big thanks :) I will try to help for the cpu

**Pull request merged**
