### PR TITLE
Added Dockerfile for Raspberry Pi 2 + 3

### PR DESCRIPTION
**Pull request by Rocka84**
using an ARM build of node

### CODE REVIEW

**Comment by philhawthorne** [comment]
Awesome! Thanks so much.

I'm going to setup Travis to automatically build each image and push it to DockerHub under the right tag. Once that's ready I'll merge this in.

Cheers

**Comment by philhawthorne** [comment]
Hey @Rocka84 

Thanks for this. I've setup Travis to build an ARM image. I had to make a couple of adjustments to get this working, and downgrade the Node JS version to V8.

Eventually I will try and get them all using the same version of Node.

Do you mind doing a quick test to ensure this is still working on your Pi? You can use the following docker run command to test the image.

```
docker run -d \
--name=ha-dockermon --restart=always \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /path/to/config:/config \
-p 8126:8126 \
philhawthorne/ha-dockermon:edge-arm
```

Once you've confirmed its working, I'll add the docs and add a `:arm` version in DockerHub.

Cheers!

**Comment by Rocka84** [comment]
Hi! 
I just tested your new version on a Raspberry Pi 3 and can confirm it still working.
To be honest: I didn't actually test this on a Raspi 2, but it similar enough to the 3 that it should work.

Greets!

**Comment by philhawthorne** [comment]
Awesome! Totally agree about the Pi2

**Pull request merged**
